### ISSUE TITLE
Doesn't work with DndProvider API react-dnd@9.3.4

### ISSUE THREAD

**Issue by Okami92** [LouisBrunner/dnd-multi-backend#33]
Am I missing something, or this library doesn't work with new react-dnd API?

I pass it like this: 

`<DndProvider backend={MultiBackend(HTML5toTouch)}>`

and receive following error:

`TypeError: manager.getActions is not a function`

**Comment by LouisBrunner** [comment]
Hi @Okami92, this bug is being tracked by #31 and is currently being worked on
